### ISSUE TITLE
External zone temperature sensor

### ISSUE THREAD

**Issue by Kingo71** [nielsfaber/zoned-heating#3]
Hi,

Is it possible to add a feature to use an external temperature sensor instead of the one in zone's thermostat? 

Thank you.
Greetings,
Angelo.

**Comment by nielsfaber** [comment]
It is not really designed for this, since the component also updates the setpoint for it.
There is no logic implemented to iskip this part.
What you could do is create a [generic thermostat](https://www.home-assistant.io/integrations/generic_thermostat/).
This toggles a switch (could be a dummy switch), based on the setpoint and value of the external sensor.

How is your experience with this component so far? Or did you not use it yet? I am asking because I see you have another (old) issue open.

**Comment by Kingo71** [comment]
Thank you for your feedback.

I did try twice to use it but both times I found some roadblocks.
Solved the first issue changing the target climate entity as I changed the firmware on my OpenTherm interface.
Now I had this other issue and couldn't use it again, is a pitty.
Reverted to previous custom component from another user.
Thank you anyway, appreciate the time spent to provide feedback.

Greetings,
Angelo.
