### ISSUE TITLE
Heating mode does not revert to original after reaching setpoint - debug log partly included

### ISSUE THREAD

**Issue by klaassybrand** [nielsfaber/zoned-heating#8]
Hello Niels,

I've been testing again lately. Currently i'm only using one extra zone (thermostaat keuken) with your zoned-heating setup.
When heating is requested from that specific zone it will nicely increase the temperature on the main thermostat controller.

Unfortunately after reaching the setpoint temperature for the zone, the main controller will not revert back to it's original setting which results in continuous heating until it eventually will reach the temperature on the main controller also, but because of it's location it takes a lot more time to heat up that room.

THis is the result in the debug log when the setpoint is reached on the zone:
![image](https://user-images.githubusercontent.com/117353642/216337131-3f909ddf-c4cf-4eec-a538-12adddabba30.png)

I hope you can help me with this one.
Thanks.

**Comment by IMMIhomeassistant** [comment]
ive got pretty much the same issue i guess, 
it starting to heat at a heat difference of X-celsius
but it took for ages to stop it, i always blamed my Moes TS0601TRV's for the PID controller
but it looks like the zoned heating is the "problem" here

i cant find on wich temp diff zoned heating starts the boiler, and on wich temp diff it stops ?

also i used the Maximum setpoint-22, but heating starts over 25degrees
so im not sure what it does ?

**Comment by nielsfaber** [comment]
@klaassybrand 
From the logs you shared I can see that:
1. the zone reached its final temperature
2. The zoned_heating integration (correctly) concluded that the override mode should be disabled (since no zones ask for heat)
3. The zoned_heating integration stops the override the mode and reverts the controller device to the prior settings

All of this looks OK to me except that step 3 fails, and results in an error.
As a result the controller stays at the setting which was calculated by the zoned_heating integration.

We can pinpoint the issue to the following code:
https://github.com/nielsfaber/zoned-heating/blob/76fdbaf002545fa5d0a7fc29bfb8fe1a44b3bdd0/custom_components/zoned_heating/switch.py#L267-L271

The `self._stored_controller_state` was set to a wrong setting.
HA gives a message that its value was not 'off', 'heat', 'cool', etc. so the question is what was is set to instead.
The value is normally set here:
https://github.com/nielsfaber/zoned-heating/blob/76fdbaf002545fa5d0a7fc29bfb8fe1a44b3bdd0/custom_components/zoned_heating/switch.py#L244

which should **always** result in a valid HVAC mode.

The other case where the variable set is after restarting HA:
https://github.com/nielsfaber/zoned-heating/blob/76fdbaf002545fa5d0a7fc29bfb8fe1a44b3bdd0/custom_components/zoned_heating/switch.py#L87

Which should result in the value it was set to prior to restarting HA, so again I would expect a valid setting.

At this point I'm not really sure what happened.
This problem does not occur for me, at this point I don't know how to reproduce this either.
Did you see the behaviour just once or multiple times?
It would be helpful to check this value at the time the error occurs:
![image](https://user-images.githubusercontent.com/16861605/218326097-34891d55-de8d-4db1-8260-39ce3f90a5ed.png)

You could also modify this line:
https://github.com/nielsfaber/zoned-heating/blob/76fdbaf002545fa5d0a7fc29bfb8fe1a44b3bdd0/custom_components/zoned_heating/switch.py#L263

Into:
```python
_LOGGER.debug("Stopping override mode. Reverting controller to mode={}".format(self._stored_controller_state))
```

To have the stored mode printed right before the error occurs.

Please let me know if you can test this and/or have some more findings to share.

@IMMIhomeassistant 
> ive got pretty much the same issue i guess,

In case you see the same error as @klaassybrand in your HA logs, this could be the case.
If no errors occur, I think you are not experiencing the same.

If you want my assistance, please enable debug logging for the zoned_heating integration by adding this to the configuration.yaml (requires restarting HA):
```yaml
  default: warning
  logs:
    custom_components.zoned_heating: debug
```
Share the loggings to be able to pinpoint the issue.
Please create a new issue if the loggings are different than what's discussed here.

> i cant find on wich temp diff zoned heating starts the boiler, and on wich temp diff it stops ?

This component checks (for every zone) temperature increase = temperature setpoint - current temperature.
Next the temperature increase is added to the current controller temperature and this is the new setpoint for the controller.
So in case your zone needs to be heated by +5 degrees, while your controller is at 17 degrees, the controller setpoint becomes 22 degrees.
This setting is kept until the state of the zone TRV changes to 'idle', meaning it reached the setpoint.

> also i used the Maximum setpoint-22, but heating starts over 25degrees

I don't know what you mean by this exactly. But this setting determines the limit of what the integration will set to the controller setpoint (so in case the limit is set at 22, the zoned_heating integration should **never** set your controller to 25 degrees).

**Comment by klaassybrand** [comment]
Thank you Niels for this helpfull answer.

I did some testing again with the added debugging for the controller state after reverting:

This is what happens, first screenshot is when heat is requested:

![image](https://user-images.githubusercontent.com/117353642/219024109-790f453f-15d2-4849-a357-c312220f2386.png)

Second when the setpoint is reached and the Override mode is being stopped, at least it should: It displays the info but it seems in my opinion the origina temperature is not being reverted (15 degrees in this case) only the "hvac_mode" seems to be reverted.
![image](https://user-images.githubusercontent.com/117353642/219024214-2b0aba46-4be4-4a45-9649-9e9c6594e34b.png)

**Comment by nielsfaber** [comment]
@klaassybrand The logging you shared initially indicated an error when setting the mode to your controller entity, so that was the focus point.
However, this error doesn't seem to occur in your recent log.
Which is not very ideal as we might have to look at 2 separate problems.

> Second when the setpoint is reached and the Override mode is being stopped, at least it should: It displays the info but it seems in my opinion the origina temperature is not being reverted (15 degrees in this case) only the "hvac_mode" seems to be reverted.

From your first screenshot I would say the controller should be reverted to 17.9C.
Maybe it's good to take a look at the history chart of the controller entity, to double-check if this was indeed the setting before the zoned-heating started (this seems to be earlier than 7:37, since the log only states that calculations were updated).
The history should also show what happened at 8:56 when the override mode stopped. Please check if the setpoint was changed at this time (mode was changed from heat to heat so I expect no change here).

You could also extend the debug logging once again (same line as before) to have also the stored setpoint show up in the log:
```
_LOGGER.debug("Stopping override mode. Reverting controller to mode={} and setpoint={}".format(self._stored_controller_state, self._stored_controller_setpoint))
```

Thanks for your patience and collaboration!

**Comment by klaassybrand** [comment]
You are correct, this error has not occured since. I'm not sure if this was related to the different heat_cool hvac mode that was used on the Climate entity.

Oke so to resume i've just run another test which should indicate the temperature is not reverting to original:
![image](https://user-images.githubusercontent.com/117353642/219154319-df39bafe-8c5a-4516-a84d-fe5621351e93.png)

**Comment by klaassybrand** [comment]
I think i have it working now! I will let you know later what seemed to do the trick.

**Comment by stinobook** [comment]
@klaassybrand just curious if you also use bbqkees mqtt controller on a EMS heating system. I also sort of have this problem but never really looked into what was causing the issue. 
For my setup i have a thermostat hc3 which controls the radiator circuit, and in the same room i also use TRV's to disable heating for that room so zoned_heating can take over that thermostat to heat other rooms.
Now since with this setup i cannot have hc3 fail to reset since it would keep heating but can never reach the temp because the TRV's are closed, i use this automation to make sure that it keeps trying to reset it (so it can be a fail in this integration, packet loss on the EMS bus or anything) 

```
alias: ZonedHeatingHC3fix
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.zoned_heating
    attribute: override_active
    from: true
    to: false
  - platform: state
    entity_id:
      - climate.thermostat_hc3
    attribute: temperature
condition:
  - condition: state
    entity_id: switch.zoned_heating
    attribute: override_active
    state: false
action:
  - repeat:
      until:
        - condition: state
          entity_id: climate.thermostat_hc3
          attribute: temperature
          state: 15
      sequence:
        - service: climate.set_temperature
          data:
            temperature: 15
          target:
            entity_id: climate.thermostat_hc3
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
    enabled: true
mode: single
```

**Comment by nielsfaber** [comment]
Closing old issues (please let me know if help is still needed).
